### ISSUE TITLE
Help command scroll page counts. 

### ISSUE THREAD

**Issue by LMByrne** [KowlinMC/PewDiePie#6]
When scrolling right through the help command, after reaching the last page (7) if you keep scrolling right the bot proceeds to duplicate the page count/total as shown below. 
![Screenshot_20190924-223620_Discord](https://user-images.githubusercontent.com/11181703/65552235-d01a3400-df1b-11e9-8e45-339d7448a5c2.jpg)

**Comment by KowlinMC** [comment]
This is a known bug. We do not currently know how to fix it.

**Comment by resynth1943** [comment]
I think I've found the error. I don't know Python, so please correct me, but [Line 103](https://github.com/KowlinMC/PewDiePie/blob/master/utils/paginator.py#L103) seems like the right place to look. 

The footer for `p.help` at page 7 has this prefix: `To become a supporter, go https://patreon.com/pdpbot | Page 7/7 | Page 7/7`, so Line 103 will never return true.

cc @KowlinMC

**Comment by KowlinMC** [comment]
hmmm didn't know that was an issue. I'll look into it, thank you.

**Comment by resynth1943** [comment]
You should learn how to use a debugger. It's a great tool (◠‿◕)
